LuaRocks 2.2.0beta1

diff --git a/luarocks/makedist b/luarocks/makedist
--- a/luarocks/makedist
+++ b/luarocks/makedist
@@ -16,40 +16,13 @@ make clean || exit 1
 
 grep -q "\"$1\"" rockspec || {
    echo
-   echo "version in rockspec is incorrect. Please fix it."
+   echo "Version in rockspec is incorrect. Please fix it."
    exit 1
 }
 
 grep -q "program_version = \"$1\"" src/luarocks/cfg.lua || {
    echo
-   echo "program_version in src/luarocks/cfg.lua is incorrect. Please fix it."
-   exit 1
-}
-
-grep -q "version: $1\\." appveyor.yml || {
-   echo
-   echo "version in appveyor.yml is incorrect. Please fix it."
-   exit 1
-}
-
-grep -q "LUAROCKS_VER: $1" appveyor.yml || {
-   echo
-   echo "LUAROCKS_VER in appveyor.yml is incorrect. Please fix it."
-   exit 1
-}
-
-# e.g. if $1 is "2.3.0", $program_series is "2.3"
-program_series=${1%.*}
-
-grep -q "program_series = \"$program_series\"" src/luarocks/cfg.lua || {
-   echo
-   echo "program_series in src/luarocks/cfg.lua is incorrect. Please fix it."
-   exit 1
-}
-
-grep -q "vars.VERSION = \"$program_series\"" install.bat || {
-   echo
-   echo "vars.VERSION in install.bat is incorrect. Please fix it."
+   echo "Version in src/luarocks/cfg.lua is incorrect. Please fix it."
    exit 1
 }
 
@@ -66,8 +39,8 @@ do
       cp "$i" "$out/$dir"
       if echo "$i" | grep -v "/bin/" | grep -q "^src/"
       then
-         grep -qw `basename "$i"` Makefile.setup.inc || {
-            echo "Missing ref in Makefile.setup.inc: $i"
+         grep -qw `basename "$i"` Makefile || { 
+            echo "Missing ref in makefile: $i"
             touch "missing_ref"
             exit 1
          }
@@ -88,14 +61,14 @@ mkdir "release-windows"
 mv "$out" "release-windows/$out-win32"
 
 cd "release-unix/$out"
-rm -rf makedist install.bat COPYING_lua COPYING_7z COPYING_win win32 lfw .travis.yml .gitignore appveyor* .appveyor
+rm -rf makedist install.bat COPYING_lua COPYING_7z COPYING_win win32 lfw .travis.yml .gitignore
 cd ..
 tar czvpf ../"$out.tar.gz" "$out"
 cd ..
 rm -rf "release-unix"
 
 cd "release-windows/$out-win32"
-rm -rf makedist Makefile* configure lfw .travis.yml .gitignore test appveyor* .appveyor
+rm -rf makedist Makefile configure lfw .travis.yml .gitignore
 cd ..
 zip -r ../"$out-win32.zip" "$out-win32"
 cd ..
